### DISCUSSION TITLE
求助

### DISCUSSION THREAD

**Discussion by sgyunc** [Qexo/Qexo#387] [Q&A] [answered]
Qexo弄好了，GitHub的自动化有没有教程啊大佬，找了几个照做都传不上去，密钥啥的都配上了，期待答案 感谢🙏

**Comment by haloged** [comment, marked as answer]
我用这个成功了
https://zhuanlan.zhihu.com/p/626270948
我给代码做了一点修改，如果没有语雀同步需求的可以直接用我这个：
```yaml
name: 自动部署
#当有改动推送到master分支时，启动Action
on:
  push:
    branches:
      - main #2020年10月后github新建仓库默认分支改为main，注意在github上更改main为master
  release:
    types:
      - published
env:
  GIT_USER: haloged
  GIT_EMAIL: {your_email}
  THEME_REPO: jerryc127/hexo-theme-butterfly #这里填你使用的主题
  THEME_BRANCH: master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检查分支
        uses: actions/checkout@v2
        with:
          ref: main #2020年10月后github新建仓库默认分支改为main，注意在github上更改main为master
      - name: Checkout theme repo #检查主题
        uses: actions/checkout@v2
        with:
          repository: ${{ env.THEME_REPO }}
          ref: ${{ env.THEME_BRANCH }}
          path: node_modules/hexo-theme-butterfly
      - name: 安装 Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x" #action使用的node版本，建议大版本和本地保持一致。可以在本地用node -v查询版本号。
      - name: 配置 环境变量
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
      - name: 安装 Hexo
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g
      - name: 缓存 Hexo
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: 安装依赖
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: |
          npm install --save
      - name: 生成静态文件
        run: |
          hexo clean
          hexo generate
      - name: 部署到Github page
        run: |
          hexo deploy
```
